export const listDerechos = [
  "Derecho a ser informado - publicamos esta Política de Privacidad para mantenerle informado sobre lo que hacemos con sus Datos Personales. Puede solicitarnos en cualquier momento los Datos Personales que conservamos sobre usted. Esta información se refiere, entre otras cosas, a las categorías de datos que tratamos, con qué fines los tratamos, el origen de los datos si no los adquirimos directamente de usted y, en su caso, los destinatarios a los que hemos enviado sus datos.",
  "Derecho de acceso - Puede preguntarnos si procesamos sus Datos Personales y tiene derecho a solicitar una copia de los datos que tenemos sobre usted.",
  "Derecho de rectificación - Tiene derecho a corregir los datos inexactos o incompletos que le concierne.",
  "Derecho al olvido - Puede solicitar que los Datos Personales que tenemos sobre usted sean borrados de nuestro sistema y cumpliremos con esta solicitud a menos que tengamos una razón legítima, un requisito legal y otra base estatutaria para no hacerlo. Aunque podamos eliminar (borrar) los Datos Personales sometidos a nuestras actividades de tratamiento activas (en curso) y cesar su tratamiento, conservaremos no obstante estos Datos Personales concretos en nuestros almacenes de copia de seguridad y archivo para cumplir nuestros requisitos legales y de otro tipo.",
  " Derecho a la restricción del tratamiento: cuando se apliquen determinadas condiciones, puede solicitarnos que 'bloqueemos' el tratamiento de sus Datos Personales.",
  " Derecho a la portabilidad de los datos - Tiene derecho a que los datos que tenemos sobre usted se transfieran a otra organización y a recibir los Datos Personales en un formato estructurado y de uso común. Diríjase a: hola@pulsodex.com.co para saber si actualmente admitimos la portabilidad del fichero que contiene los Datos Personales que tratamos sobre usted.",
  " Derecho de oposición - Puede oponerse al tratamiento de sus datos solicitándolo a: info@pulsodex.com.co en cualquier momento por motivos que se deriven de su situación particular siempre que el tratamiento de datos se base en nuestro interés legítimo o en el de un tercero, o cuando llevemos a cabo la elaboración de perfiles, utilizamos algoritmos de aprendizaje automático o de toma de decisiones automatizada. En este caso, dejaremos de tratar sus Datos Personales. Esto último no se aplica si podemos demostrar que existen razones imperiosas y defendibles para el tratamiento que prevalecen sobre sus intereses o necesitamos sus datos para hacer valer, ejercer o defender reclamaciones legales.",
  "Derecho a retirar el consentimiento: retirar el consentimiento que nos dio con respecto al tratamiento de sus Datos Personales para determinados fines.",
  "Derecho a reclamar: nos tomamos muy en serio sus derechos. No obstante, si considera que no hemos tramitado sus reclamaciones adecuadamente, tiene derecho a presentar una queja ante las autoridades responsables de la protección de datos. Puede enviar sus quejas a la autoridad de control del EEE de su país de residencia.",
];
