import { Inter } from "next/font/google";
import "../(front)/globals.css";
// import "./globals.css";

import CardSideNav from "./components/CardSideNav";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "PulsoDex",
    description: "Generated by create next app",
};

export default function Layout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="flex  flex-col md:flex-row md:overflow-hidden bg-[#FAFAFA]">
                    <div className="">
                        <CardSideNav/>
                    </div>
                    <div className="flex-grow p-6 md:overflow-auto md:p-8">{children}</div>
                </div>      
            </body>
        </html>
    );
}